version: "3.7"
services:
  jupyter-lab:
    build: .
    init: true
    image: realappsdev/tf:latest
    ports:
      - "8888:8888"
    volumes:
      - jupyter_lab_app:/opt/conda/share/jupyter/lab
      - jupyter_lab_config:/root/.jupyter
      - /data/jupyter-lab:/jupyter-lab

volumes:
  jupyter_lab_app:
    external: true
  jupyter_lab_config:
    external: true
